# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more info see: https://help.github.com/actions/language-and-frameworks-guides/using-nodejs-with-github-actions

name: Cypress Test Culture

on:  
  push:
    branches: 
    - 'master'
    
    
jobs:
  build:    
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: gauravkb
      LT_ACCESS_KEY: hUV2fq7Xb0SlFDRL1cwE8bcx71P0hImMJR0aaqN8groMUYzVLJ
    steps: 
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2       
        with:          
          node-version: 12     
      - run: npm install -g lambdatest-cypress-cli
      - run: lambdatest-cypress init
      - run:
          echo "The LT_USERNAME na"
          lambdatest-cypress --version
      - run: lambdatest-cypress run --envs="c=2,baseurl=https://accounts.lambdatest.com/login"



          
        
