# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Sample

on:
  push:
    branches: 
    - 'master'

jobs:
  Cypress-Sample:
    name: Run on Chrome 92
    runs-on: window10
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - uses: actions/checkout@v2
      - name: Install cypress and verify
        run:
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress Tests
        run: npm run test:chrome
        continue-on-error: false
        
      - name: copy test execution video and screenshots
        run: 
          mkdir public
          cp -r cypress/video public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run combine:reports
        
      - name: Generate HTML reports
        run: npm run generate:reports
        
      - name: Deploy report page to Github Page
        uses: peaceiris/actions-gh-page@v3
        with:
          githiub_token: ${{ secrets.GITHIB_TOKEN}}
          publish_dir: ./public
        
