# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Sample

on:
  push:
    branches: 
    - 'master'

jobs:
  Cypress-Sample:
    name: Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM and Cypress
        run:
          npm install
          npm install -g lambdatest-cypress-cli
          
#       - name: Use Node.js vnode16.5.0
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12

      - name: generate LambdaTest Config
        run:
          lambdatest-cypress init
          
      - name: Set ENV variables
        env:
          # pass the Dashboard record key as an environment variable
          LT_USERNAME: "gauravkb"
          LT_ACCESS_KEY: "DqLVVOF1ll4TTMyXXt3gslp8NZ8Ynon3vwcRd4eFTV5GLavGh9"
        
      - name: copy test execution video and screenshots
        run: 
          mkdir public
          cp -r cypress/video public/videos
          cp -r cypress/screenshots public/screenshots
        
        
      # Starts local server, then runs Cypress tests and records results on the dashboard
      - name: Cypress tests
        run: |
          lambdatest-cypress run
        
